### ISSUE TITLE
在visual 2017 下编译， 无法发现设备

### ISSUE THREAD

**Issue by hanqingwu** [xindawndev/xindawn-windows-airplay-mirroring-sdk#4]
1. 下载代码。
2.  打开.sln 到 visual 2017.
3.  编译，去除 __imp__fprintf和__imp____iob_func   错误 。
4.  运行， cmd netstat -ano 发现有占用5353端口
5.  连入的IOS设备发起5353请求，从wireshark 看，本程序没有回应。 IOS设备无法发现AirPlay 设备。

**Comment by xindawndev** [comment]
需要安装bonjour

hanqingwu <notifications@github.com>于2017年8月9日 周三上午11:18写道：

**Comment by hanqingwu** [comment]
安装bonjour 了，可以发现设备，但IOS设备 Airplay 选择xindawn 时，提示无法连接设备。

**Comment by xindawndev** [comment]
Please make sure the system date and time are correct！

2017-08-09 16:47 GMT+08:00 hanqingwu <notifications@github.com>:

**Comment by dev-goalz** [comment]
The problem is this part.

`#if (_MSC_VER == 1900)`

For 2017 it should be :
```
#if (_MSC_VER >= 1900) 
```

**Comment by hanqingwu** [comment]
yes ,it's ok now !
